FROM ghcr.io/browncs1952y/cs1952y-devenv-test4:latest

# clone Ripes repo
RUN mkdir -p /home/cs1952y-user && git clone --recursive https://github.com/browncs1952y/Ripes-1952y /home/cs1952y-user/Ripes

# build ripes from source
RUN cd /home/cs1952y-user/Ripes &&\
  cmake . -DCMAKE_PREFIX_PATH=/deps/Qt6.8.0/install &&\
  make -j8
