FROM ghcr.io/browncs1952y/cs1952y-devenv-test1:latest

# install riscv-gnu-toolchain
RUN mkdir -p /deps/riscv && git clone https://github.com/riscv/riscv-gnu-toolchain /deps/riscv

RUN export PATH="$PATH:/opt/riscv" && cd /deps/riscv && ./configure --prefix=/opt/riscv --enable-multilib && make > /dev/null

RUN rm -rf /deps/riscv

# RUN echo "export PATH=\"\$PATH:/opt/riscv\"" >> /home/cs1952y-user/.bashrc
