FROM ubuntu:jammy

RUN apt-get update &&\
  yes | unminimize &&\
  apt-get -y install\
  autoconf automake autotools-dev curl python3 python3-pip python3-tomli\
  libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo\
  gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake\
  libglib2.0-dev libslirp-dev libncurses-dev

RUN mkdir /deps/riscv && git clone --depth 1 https://github.com/riscv/riscv-gnu-toolchain /deps/riscv &&\
  cd /deps/riscv && ./configure --prefix=/opt/riscv --enable-multilib --enable-strip &&\
  make -j4 > /dev/null && rm -rf /deps/riscv
