FROM ghcr.io/browncs1952y/cs1952y-devenv-test3:latest

RUN mkdir -p /deps/mold &&\
    git clone --branch stable https://github.com/rui314/mold.git /deps/mold
    
RUN cd /deps/mold &&\
    ./install-build-deps.sh &&\
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=c++ -B build &&\
    cmake --build build -j$(nproc) &&\
    sudo cmake --build build --target install