FROM ghcr.io/browncs1952y/cs1952y-devenv-test5:latest

RUN git clone https://github.com/browncs1952y/gem5-assignments-stencil /home/cs1952y-user/gem5 &&\
  mkdir /gem5_build /gem5_cache

RUN cd /home/cs1952y-user/gem5 &&\
  scons defconfig /gem5_build build_opts/RISCV --ignore-style &&\
  scons setconfig /gem5_build USE_KVM=y --ignore-style &&\
  scons setconfig /gem5_build M5_BUILD_CACHE=/gem5_cache --ignore-style &&\
  scons /gem5_build/gem5.debug -j8 --linker=mold --limit-ld-memory-usage --ignore-style